### ISSUE TITLE
[BUG] Can't add externally referenced JSON schema files

### ISSUE THREAD

**Issue by JaredCE** [JaredCE/serverless-openapi-documenter#10]
**Describe the bug**
At the moment you can't add externally referenced JSON schema files, all JSON schema files either have to be internally written or available at the time of parsing in the file system.

**To Reproduce**
```
serverless.yml
service: abc
provider:
  name: aws

custom:
  documentation:
    description: abc
    version: 1.0.0
    models:
      - name: externalFile
      - description: An external definition
      - contentType: application/json
      - schema: https://raw.githubusercontent.com/JaredCE/serverless-openapi-documenter/main/test/models/ErrorResponse.json
```
**Expected behavior**
The externally referenced JSON schema should be pulled in to the components object in the right place.

**Desktop:**
 - Serverless version: all
 - serverless-openapi-documenter version 0.0.7
