### ISSUE TITLE
Ability to optionally skip documenting some functions 

### ISSUE THREAD

**Issue by Tee88** [JaredCE/serverless-openapi-documenter#110]
I have more than one serverless function, but only want to add documentation to a subset of those functions. But when I run
`npx serverless openapi generate -f json -o ./docs/api/openapi.json` I get this error:

`Configuration error at 'functions.myFunction.events.0.http': must have required property 'documentation'`

**Comment by JaredCE** [comment]
Which version of serverless are you running?

When I run it on version 3.21.0 with a serverless configuration like:

```
functions:
  createUser:
    handler: handler.create
    events:
      - http:
          path: create/{username}
          method: post
          documentation:
            summary: Create User
            description: Creates a user and then sends a generated password email
            ...
  deleteUser:
    events:
      - http:
          path: delete/
          method: delete
```

I receive:

> Warning: Invalid configuration encountered
  at 'functions.deleteUser.events.0.http': must have required property 'documentation'

This doesn't stop the openAPI from generating, nor serverless from working.  The warning is just there to say/coax you into having a `documentation` tag for an endpoint.

**Comment by JaredCE** [comment]
Hey @Tee88 did the above help?

**Comment by JaredCE** [comment]
I'm going to close this, but do re-open and let me know if it remains an issue.

**Comment by JaredCE** [comment]
Ok, I think this is related to `configValidationMode` set in your serverless file? https://www.serverless.com/framework/docs/configuration-validation

I never set mine, so it defaults to Warn.  I'll have to go in and take a look

**Comment by JaredCE** [comment]
As of release 0.0.66, you now don't need to provide the documentation tag on `http`/`httpApi` event functions.  It'll only complain if you do provide the, but don't specify `methodResponses`.

```yml
functions:
  createUser:
    handler: handler.create
    events:
      - http:
          path: create/{username}
          method: post
          documentation:
            summary: Create User
            description: Creates a user and then sends a generated password email
  deleteUser:
    events:
      - http:
          path: delete/
          method: delete
```
So in the above example, deleteUser will not cause an error, but createUser would as it's only partially documented and does not contain a methodResponses array.
