### ISSUE TITLE
TypeError: this.documentation?.models?.map is not a function

### ISSUE THREAD

**Issue by mikedambrogia** [JaredCE/serverless-openapi-documenter#120]
I'm new to openapi and this plug-in, so it's nearly certain that is pilot error/lack of understanding on how to implement it

I'm supporting an existing Serverless app that has ~ 12 active endpoints

I have the plug-in in my serverless.yml file located after the serverless-offline as noted in the install section of the README

I'm attempting to get enough boilerplate into the yml file to get the "sls openapi generate ..." cmd to generate a yml file that will be full of dummy data/garbage, and once I get to this point I can start adding in actual documentation key/value pairs for my endpoints 1x1 over time

I'm essentially just copy/paste off of the doc page for the custom: section and the function events: section/s for each of my endpoints

For this effort I don't need anything more that the bare minimums 

custom:
```
  documentation:
    version: '1'
    title: 'My API'
    description: 'This is my API'
    models: { }
    externalDocumentation:
      url: https://google.com
      description: A link to google
    servers:
      url: https://example.com
      description: The server
    tags:
      - name: tag1
        description: this is a tag
        externalDocumentation:
          url: https://npmjs.com
          description: A link to npm
```

and in each of the ~12 function/event section, I've added this exact same documentation code snippet under the existing events/http section 
```
  events:
    - http:
        path: path_to_my_existing_function/action/{param1}/{param2}
        method: delete
        cors:
          origin: '*'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - X-Auth-Token
        documentation:
          summary: "Create User"
          description: "Creates a user and then sends a generated password email"
          requestBody:
            description: "A user information object"
          requestModels:
            application/json: "PutDocumentRequest"
          queryParams:
            - name: "membershipType"
              description: "The user's Membership Type"
              schema:
                type: "string"
                enum:
                  - "premium"
                  - "standard"
          methodResponses:
            - statusCode: 201
              responseBody:
                description: "A user object along with generated API Keys"
              responseModels:
                application/json: "PutDocumentResponse"
            - statusCode: 500
              responseBody:
                description: "An error message when creating a new user"
              responseModels:
                application/json: "ErrorResponse"
```
The documentation section above is taken off the README page

The error
```
$: serverless openapi generate -o openapi_test.yml -f yaml -a 3.0.3 --stage mike
Running "serverless" from node_modules
OpenAPI v3 Document Generation
[OPTIONS]
  openApiVersion: "3.0.3"
  format: "yaml"
  output file: "openapi_test.yml"
  indentation: "2"
  
Environment: linux, node 16.16.0, framework 3.30.1 (local) 3.30.1v (global), plugin 6.2.3, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: this.documentation?.models?.map is not a function

```

I could use a point in the right direction, TIA

**Comment by JaredCE** [comment]
Hey @mikedambrogia 

So, rightly or wrongly, the plugin does require some models to be listed.  You don't need to use `requestBody` and `requestModels` for now, but you'll need to make some `responseModels`.

Within your `custom: documentation:` where you have `models: { }`, you should probably just add a dummy model for now, something like:

```yml
custom:
  documentation:
    ...
    models:
      - name: "ErrorResponse"
        description: "This is an error"
        contentType: "application/json"
        schema: 
          type: object
          properties:
            error:
              type: string
```

Then change where all your function documentation, under the `methodResponses` to read:

```yml
responseModels:
  application/json: "ErrorResponse"
```

The Error that you've brought up needs looking at and i need to produce a better error message, but the above should fix your issue for now.

**Comment by JaredCE** [comment]
If you do use, `requestModels`, just refer to **ErrorResponse** or whatever you might have called your dummy Model.

**Comment by mikedambrogia** [comment]
thx for the quick response

I did replace the models: {} with a model similar to what you'd outlined, and got past the initial error I reported

I've added PutDocumentRequest, PutDocumentResponse, and ErrorDocument files in the root of the project, and added some garbage json to get them to fly.  Getting some assert errors in one of my functions, but I know which one to dig in on from the error message

Is there a way to tell the plug in to ignore, or not look in an endpoint, for an event/documentation?  Some sort of include or exclude list to restrict things a bit?  

I'd like to just work on 1 endpoint and get it working, THEN clone it over into the others.  But the `generate` errors out with a "missing documentation" error on each endpoint where there is no documentation node in the functions events

**Comment by JaredCE** [comment]
It should just be a warning rather than an error? Is it failing to generate
the documentation?

Generally speaking you can either not add a `documentation` property to a
function or just comment out `documentation` and everything below, it'll
warn that your functions are missing documentation properties, but should
still generate documentation for the ones you have left in.

It's getting up to midnight in the UK, so responses will probably be in the
morning after this one.  Please do log bugs, especially if you feel the
README is not as clear as it could be.

Cheers

**Comment by JaredCE** [comment]
Hmmm someone opened this issue about that: https://github.com/JaredCE/serverless-openapi-documenter/issues/110

I didn't get any further with it and so closed it as I couldn't quite replicate it.  I don't get why it's outputting two different error messages.  I'll have to try digging into it further.

**Comment by JaredCE** [comment]
Oh I wonder, do you have: `configValidationMode` set in your serverless file?  https://www.serverless.com/framework/docs/configuration-validation 

I don't set mine, so it's set to "warn"... hmm ok I think i might need to sort this somehow.

**Comment by mikedambrogia** [comment]
Set configValidationMode: off  (warn gives the exact same output)

And then commented out all "documentation:" sections in all the functions.  Gave me:

```
OpenAPI v3 Document Generation
[OPTIONS]
  openApiVersion: "3.0.3"
  format: "yaml"
  output file: "openapi_test.yml"
  indentation: "2"
  
✔ OpenAPI v3 Documentation Successfully Generated
✔ OpenAPI v3 Documentation Successfully Written
```
I get the output from the custom/documentation: section in the generated yml file, and the file loads and displays correctly

**Comment by mikedambrogia** [comment]
this is the minimum required config settings for the plug-in in serverless.yml:
```
configValidationMode: warn
custom:
  documentation:
    title: 'My API'
```
generates a valid openApi doc
