### ISSUE TITLE
[BUG] Variable resolution from serverless compose crashing plugin

### ISSUE THREAD

**Issue by veigajoao** [JaredCE/serverless-openapi-documenter#123]
**Describe the bug**
When using the plugin within a `serverless.yaml` that is a part of a compose project, the plugin cannot resolve the injected variables from compose, causing it to crash - even though variables are entirely irrelevant for the generation of documentation

**To Reproduce**
```
# main serverless.yml
service: auth

provider:
  name: aws
  stage: dev
  region: sa-east-1
  runtime: nodejs18.x
  apiGateway:
    restApiId: ${param:ApiGW}
    restApiRootResourceId: ${param:ApiGWRootResourceId}
    websocketApiId: ${param:WebsocketsApi}
  environment:
    USER_POOL_ID: !Ref UserPool
    CLIENT_ID: !Ref UserPoolClient
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminAddUserToGroup
            - cognito-idp:AdminListGroupsForUser
          Resource: !GetAtt UserPool.Arn

functions:
  signup:
    handler: src/signup.handler
    events:
      - http:
          path: auth/signup
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.signup}

  requestVerifyEmail:
    handler: src/requestVerifyEmail.handler
    events:
      - http:
          path: auth/requestVerifyEmail
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.requestVerifyEmail}

  verifyEmail:
    handler: src/verifyEmail.handler
    events:
      - http:
          path: auth/verifyEmail
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.verifyEmail}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt UserPool.Arn

  login:
    handler: src/login.handler
    events:
      - http:
          path: auth/login
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.login}

  refresh:
    handler: src/refresh.handler
    events:
      - http:
          path: auth/refresh
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.login}

  forgotPassword:
    handler: src/forgotPassword.handler
    events:
      - http:
          path: auth/forgotPassword
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.forgotPassword}

  resetPassword:
    handler: src/resetPassword.handler
    events:
      - http:
          path: auth/resetPassword
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.resetPassword}

  changePassword:
    handler: src/changePassword.handler
    events:
      - http:
          path: auth/changePassword
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.changePassword}
  
  privateAPI:
    handler: src/private.handler
    events:
      - http:
          path: auth/private
          method: post
          cors: true
          documentation: ${file(docs/serverless.doc.yaml):endpoints.privateAPI}
          authorizer:
            name: PrivateAuthorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt UserPool.Arn

  idTokenGeneration:
    handler: src/idTokenGeneration.handler
    events:
      - cognitoUserPool:
          pool: ${self:service}-pool-${sls:stage}
          # pool: !GetAtt UserPool.Name
          trigger: PreTokenGeneration
          existing: true

resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-pool-${sls:stage}
        Schema:
          - Name: email
            Required: true
            Mutable: true
          - Name: admin
            DeveloperOnlyAttribute: true
            AttributeDataType: String
            Mutable: false
            Required: false
        Policies:
          PasswordPolicy:
            MinimumLength: 6
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE

    CognitoUserPoolGroupAdmin:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Admin priviledges"
        GroupName: "admin"
        UserPoolId: !Ref UserPool

    CognitoUserPoolGroupMaintainer:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Access to admin functions only when approved by admins"
        GroupName: "maintainer"
        UserPoolId: !Ref UserPool

    CognitoUserPoolGroupPhysician:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Access to physician functions"
        GroupName: "physician"
        UserPoolId: !Ref UserPool

    CognitoUserPoolGroupPatient:
      Type: AWS::Cognito::UserPoolGroup
      Properties: 
        Description: "Regular users"
        GroupName: "patient"
        UserPoolId: !Ref UserPool

    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-pool-client-${sls:stage}
        GenerateSecret: false
        UserPoolId: !Ref UserPool
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
          # - REFRESH_TOKEN_AUTH

    # CognitoUserPoolIdentityProvider:
    #   Type: AWS::Cognito::UserPoolIdentityProvider
    #   Properties: 
    #     ProviderName: Google
    #     AttributeMapping:
    #       email: emailAddress
    #     ProviderDetails:
    #       client_id: ${env:GOOGLE_CLIENT_ID}
    #       client_secret: ${env:GOOGLE_CLIENT_SECRET}
    #       authorize_scopes: email name openid
    #     ProviderType: Google
    #     UserPoolId: !Ref UserPool

plugins:
  - serverless-esbuild
  - serverless-openapi-documenter
  - serverless-stack-output

package:
  individually: true

custom:
  documentation: ${file(docs/serverless.doc.yaml):documentation}

  output:
    file: ../.serverless/stack.json

  esbuild:
    bundle: true
    minify: true
```

```
# serverless-compose.yaml
services:
  rest:
    path: rest

  auth:
    path: auth
    params:
      ApiGW: ${rest.ApiGW}
      ApiGWRootResourceId: ${rest.ApiGWRootResourceId}
      WebsocketsApi: ${rest.WebsocketsApi}
```

```
# reat service serverless.yaml
service: rest-api

provider:
  name: aws
  stage: dev
  region: sa-east-1
  runtime: nodejs18.x

resources:
  Resources:
    ApiGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ApiGW

    WebsocketsApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: WebsocketsApi
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: '$request.body.action'

  Outputs:
    ApiGW:
      Value: !Ref ApiGW

    ApiGWRootResourceId:
      Value: !GetAtt ApiGW.RootResourceId

    WebsocketsApi:
      Value: !Ref WebsocketsApi
```

**Expected behavior**
The expected behavior is for the `serverless openapi generate` to generate the documentation. If I remove the injected variables from `serverless-compose` it works just fine. When I run the command with the `serverless-compose`setup however, I get the following errors:

```
# When running from serverless-compose folder
The variable "${rest.ApiGW}" cannot be resolved: the referenced output does not exist.
```
```
# When running from auth service folder
Cannot resolve serverless.yaml: Variables resolution errored with:
  - Cannot resolve variable at "provider.apiGateway.restApiId": The param "ApiGW" cannot be resolved from CLI options or stage params. If you are using Serverless Framework Compose, make sure to run commands via Compose so that all parameters can be resolved,
  - Cannot resolve variable at "provider.apiGateway.restApiRootResourceId": The param "ApiGWRootResourceId" cannot be resolved from CLI options or stage params. If you are using Serverless Framework Compose, make sure to run commands via Compose so that all parameters can be resolved,
  - Cannot resolve variable at "provider.apiGateway.websocketApiId": The param "WebsocketsApi" cannot be resolved from CLI options or stage params. If you are using Serverless Framework Compose, make sure to run commands via Compose so that all parameters can be resolved
```

**Desktop (please complete the following information):**
 - Serverless version: 3.32.2
 - serverless-openapi-documenter version 0.0.65

**Additional context**
I am using a pnpm monorepo folder structure where I have a parent `microservices` folder, that holds `serverless-compose.yaml` and I have one child directory for each individual service, each of them hold their respective `serverless.yaml`.
