### ISSUE TITLE
optional path parameter 

### ISSUE THREAD

**Issue by Exy63** [JaredCE/serverless-openapi-documenter#128]
I would like to have specifications like this:
```
{
  "name": "versionId",
  "in": "path",
  "description": "Id of the version. Uses the latest version by default.",
  "required": false, #!
  "schema": {
    "$ref": "#/components/schemas/versionId"
  }
},
```
But since `required: false` is not supported for path parameters it seems impossible. 
```
- name: versionId
  description: 'Id of the version. Uses the latest version by default.'
  required: false # doesn't work
  schema:
    type: string
```
With the config above I have this as an output
```
{
  "name": "versionId",
  "in": "path",
  "description": "Id of the version. Uses the latest version by default.",
  "required": true,
  "schema": {
    "$ref": "#/components/schemas/versionId"
  }
},
```

Could you tell me please there is any workaround for my case? 
I can apply those changes manually but after using the plugin they are disappeared
