### ISSUE TITLE
[BUG] serverless.yml endpoint description "leaks" into OpenAPI paths object

### ISSUE THREAD

**Issue by karmaniverous** [JaredCE/serverless-openapi-documenter#147]
**Describe the bug**

The description property from the `serverless.yml` endpoint definition will sometimes "leak" into the OpenAPI paths object.

For example:

```js
{
  get: {
    summary: "Get OpenAPI docs",
    description: "Get JSON-formatted OpenAPI documentation.",
    operationId: "publicGetDocOpenapi",
    parameters: [ ... ],
    tags: [ ... ],
    responses: { ... },
  },
  description: "OpenApi documentation get endpoint handler.", // NOT an endpoint!!
}
```

We were able to correct for this issue post-generation until your `0.0.80` release, where new function `cleanupLinks` fails at [this line](https://github.com/JaredCE/serverless-openapi-documenter/blob/46210a7b6afd57b53b0c33ec7dfee41864d38e98/src/definitionGenerator.js#L912) as the spurious `description` property is not an object.

**To Reproduce**

Not entirely sure. We are having the same issue across 15 repos using this plugin, and it has been with us from the beginning. I'd love to know how NOT to reproduce this issue.

Here is the `serverless.yml` definition of an endpoint that produces this effect:

```yml
  public-doc-openapi-get:
    description: OpenApi documentation get endpoint handler.
    events:
      - http:
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.querystring.excludeEndpoints
              - name: request.querystring.includeEndpoints
              - name: request.querystring.excludeTags
              - name: request.querystring.includeTags
          cors: true
          documentation: ${file(serverless.doc.merged.yml):endpoints.public.doc-openapi-get}
          method: get
          path: doc/openapi
      - http:
          method: head
          path: doc/openapi
    handler: lib/lambda/endpoint/doc/openapi/get/public.handler
    name: ${env:STACK_NAME}-public-doc-openapi-get
    provisionedConcurrency: 0
```

And here is the snippet at the documentation link:

```yml
  endpoints:
    public: &EndpointsPublicCommon
      doc-openapi-get:
        summary: Get OpenAPI docs
        description: Get JSON-formatted OpenAPI documentation.
        methodResponses:
          - statusCode: 200
            responseBody:
              description: JSON-formatted OpenAPI documentation.
            responseModels:
              application/json:
                schema:
                  type: object
        operationId: publicGetDocOpenapi
        queryParams:
          - name: excludeEndpoints
            description:
              "A tilde (~) delimited list of endpoint tags. Endpoints with these tags will be excluded from the result. \
              This parameter is mutually exclusive with `includeEndpoints`."
            schema:
              type: string
          - name: excludeTags
            description:
              "A tilde (~) delimited list of endpoint tags. These tags will be stripped from the result. \
              This parameter is mutually exclusive with `includeTags`."
            schema:
              type: string
          - name: includeEndpoints
            description:
              "A tilde (~) delimited list of endpoint tags. Only endpoints with these tags will be included in the result. \
              This parameter is mutually exclusive with `excludeEndpoints`."
            schema:
              type: string
          - name: includeTags
            description:
              "A tilde (~) delimited list of endpoint tags. All other tags will be stripped from the result. \
              This parameter is mutually exclusive with `excludeTags`."
            schema:
              type: string
        tags:
          - Public
          - Doc
```

**Expected behavior**

I expected the spurious `description` property (although I don't want it) but I did NOT expect the internal error produced by `cleanupLinks`. 

**Desktop (please complete the following information):**
 - Serverless version: 
   - Framework Core: 3.32.2 (local) 3.34.0 (global)
   - Plugin: 6.2.3
   - SDK: 4.3.2
 - serverless-openapi-documenter version [e.g. 0.0.80]

**Additional context**

A nice outcome of this would be the elimination of that spurious description tag. That thing is a real pain in the butt.
