### ISSUE TITLE
[BUG] Error is generated after upgrading from 0.0.63 to 0.0.64

### ISSUE THREAD

**Issue by john-mills-nz** [JaredCE/serverless-openapi-documenter#165]
**Describe the bug**
The following error is generated after upgrading from v0.0.63 to v0.0.64. The error also occurs in v0.0.90.

> OpenAPI v3 Document Generation
> [OPTIONS]
>   openApiVersion: "3.0.0"
>   format: "yaml"
>   output file: "openapi.yml"
>   indentation: "2"
> 
> 
> 
> ✖ ERROR: An error was thrown generating the OpenAPI v3 documentation
> Environment: linux, node 18.16.0, framework 3.22.0 (local), plugin 6.4.0, SDK 4.4.0
> Docs:        docs.serverless.com
> Support:     forum.serverless.com
> Bugs:        github.com/serverless/serverless/issues
> 
> Error:
> ServerlessError: Error: Expected a file path, URL, or object. Got undefined

**To Reproduce**
```
npx serverless openapi generate --format yaml --output openapi.yml
```
**Expected behavior**
To complete successfully

**WSL on Windows 10:**
 - Serverless version: 3.22
 - serverless-openapi-documenter version 0.0.64 - 0.0.90

**Comment by john-mills-nz** [comment]
Updated serverless to v3.36.0. Still generates an error for v0.0.64 - v.0.0.90.

**Comment by JaredCE** [comment]
Hey @john-mills-nz is there a chance you can produce a minimum viable reproduction.  I use this package and version of serverless extensively and haven't found any errors.

**Comment by john-mills-nz** [comment]
Hi @JaredCE 

I've isolated it down to the responseModels on a particular lambda that returns HTML.

```
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: OK
                responseModels:
                  application/html: ""
```

If I change the `application/html: ""` line to `application/json: {}` then the generating the documentation completes without error.

**Comment by john-mills-nz** [comment]
Looks like the issue was in our configuration. It was written some time ago.

I changed it to:

```
    methodResponses:
      - statusCode: 200
        responseBody:
          description: OK
        responseModels:
          text/html: HtmlModel
```
...
```
   models:
    - name: HtmlModel
      contentType: text/html
      schema:
        type: string
```

I'm now able to get it running under v0.0.84. Got some other issues to address now under v0.0.90 😄
