### ISSUE TITLE
[FEATURE] Support APIS not defined under  functions.funcName.events[http or httpApi]

### ISSUE THREAD

**Issue by avatarrosh** [JaredCE/serverless-openapi-documenter#166]
First of all, thank you for this plugin!
I'm currently working on a serverless project that uses another plugin (serverless-apigateway-service-proxy). This plugin allows to define some APIs endpoint outside of the _functions_ section, like this:
```
custom:
   apiGatewayServiceProxies:
      - sns:
          path: /testEndpoint
          method: post
          topicName: SNStopic
          request:
             template:
             ...
```
I need to generate documentation also for these endpoints. Is there a way to achieve this?
Thank you
