### ISSUE TITLE
How to debug when adding to a project?

### ISSUE THREAD

**Issue by slatermorgan** [JaredCE/serverless-openapi-documenter#184]
Hi there, not sure if this is an acceptable place to be raising this issue.

I have a project using `serverless-aws-documentation` already, so I expect this should mostly work without too much configuration chage.

I have a `serverless.yml` file and then I import commonly reused serverless configuration from other files using `serverless-import-plugin` (https://www.serverless.com/plugins/serverless-import-config-plugin).

```
service: '${env:APINAME}-V1'

plugins:
  - serverless-import-plugin
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-openapi-documenter
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-api-gateway-caching

provider:
  name: aws
  environment: ${file(../../../serverless/environment.yml)}
  stage: ${sls:stage, self:custom.default.stage}
  region: ${opt:region,  self:custom.default.region}

custom:
  default:
    stage: dev
    region: eu-west-1

  documentation:
    version: "1"
    title: "My API"
    description: "This is my API"

  import:
    - another/service/v1
    - ../../../common.yml
``` 

This works fine for `serverless-aws-documentation` however when I go to import my function declarations (in another serverless file) I get the following error:

```
Generating OpenAPI Description
✖ ERROR: An error was thrown generating the OpenAPI v3 Description
Environment: darwin, node 18.7.0, framework 3.36.0 (local) 3.34.0v (global), plugin 7.1.0, SDK 4.4.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
ServerlessError: TypeError: Cannot read properties of undefined (reading 'description')

2 deprecations found: run 'serverless doctor' for more details
Error: 

``` 

Is there any way of working out which line number this could be?

Without the line number, or any indication of where that undefined is, I'm finding it impossible to debug. I suspect this is due to conflicts with `serverless-import-plugin`.

**Comment by JaredCE** [comment]
There isn't an easy way to debug and i do need to make error output a lot better.

I think you're probably getting this issue because you do not have a 
```
requestBody:
  description: "A user information object"
requestModels:
  application/json: "PutDocumentRequest"
```

properly defined.

**Comment by slatermorgan** [comment]
My only endpoint I am including is a GET, so I don't think it can be that.

```
        methodResponses:
          - statusCode: "200"
            responseModels:
              "application/json": "ProductsProduct"
          - statusCode: "404"
            responseModels:
              "application/json": "ProductsServiceError"
          - statusCode: "400"
            responseModels:
              "application/json": "ProductsServiceError"
```

Is it safe to say the responseModels should also have a decription too? 

However the models themselves do have the description:
```
name: "Product"
description: "A Product"
contentType: "application/json"
schema:
  properties:
    id:
      description: "The product id"
      type: "string"
    slug:
      description: "The product's slug"
      type: "string"
```
      
Please take model naming with a pinch of salt, I have a pre-compile script which moves things around and renames them slightly.

Everything works with `serverless-aws-documentation` V1.1.0 so wondering if there is a slight syntax difference.
      
Any help much appreciated!

**Comment by JaredCE** [comment]
Ahh yes

you'll need to add a `responseBody`:
```
methodResponses:
  - statusCode: 200
    responseBody:
      description: Filtered Results
    responseModels:
      application/json: ReadFilterResponse
```

it's because i'm assuming there is a `responseBody.description` rather than doing a `responseBody?.description`

**Comment by slatermorgan** [comment]
That was it thanks for taking the time to resonse!

I'm thinking of adding this to a very large serverless application (14 services) so your help is hugely appreciated.

**Comment by slatermorgan** [comment]
Now I am getting"
```
Generating OpenAPI Description
✖ ERROR: An error was thrown generating the OpenAPI v3 Description
Environment: darwin, node 18.7.0, framework 3.36.0 (local) 3.34.0v (global), plugin 7.1.0, SDK 4.4.0
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
ServerlessError: ResolverError: Error opening file "/my-big-project/services/v1/products/ProductsProduct" 
ENOENT: no such file or directory, open '/my-big-project/services/v1/products/ProductsProduct'

2 deprecations found: run 'serverless doctor' for more details
Error: 
```

I assume this is some nuance with my file structure.

**Comment by JaredCE** [comment]
that does look like a file structure issue.  

so you have your responses like:

```
methodResponses:
          - statusCode: "200"
            responseModels:
              "application/json": "ProductsProduct"
```

`ProductsProduct` should be pointing to something in  your custom settings

```
custom:
  documentation:
    ...
    models:
      - name: ProductsProduct
         content:
          application/json:
            schema: 
```
and schema can be like a ref to a local file: `${file(./schemas/createSchema.json)}` which serverless will resolve i think, or a url like: `http://${self:custom.schemaBucket.${opt:stage}}/build/Organisation.json` which i try and resolve.
