### ISSUE TITLE
[BUG] TypeError generating OpenAPI with Request Schema Validators

### ISSUE THREAD

**Issue by okonomi** [JaredCE/serverless-openapi-documenter#245]
**Describe the bug**

I configured it according to "Serverless Request Schema Validators" in the README, but an error occurred.

https://github.com/JaredCE/serverless-openapi-documenter?tab=readme-ov-file#serverless-request-schema-validators

**To Reproduce**

`serverless.yml` is as follows:

```yaml
service: serverless-openapi-doc-demo
frameworkVersion: "4"
provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    request:
      schemas:
        user:
          name: User
          schema:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              email:
                type: string

plugins:
  - serverless-openapi-documenter

custom:
  documentation:
    version: 1.0.0

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          request:
            schemas:
              application/json: user
          documentation:
            methodResponses:
              - statusCode: 201
              - statusCode: 400
```

**Expected behavior**

run this command:

`npx sls openapi generate --output openapi.json`

and raise this error:

```
OpenAPI v3 Description Generation
[OPTIONS]
  openApiVersion: "3.0.0"
  format: "json"
  output file: "openapi.json"
  indentation: "2"
  validationWarn: false

Generating OpenAPI Description
✖ ERROR: An error was thrown generating the OpenAPI v3 Description

✖ ServerlessError2: ServerlessError2: TypeError: Cannot convert undefined or null to object
    at /Users/okonomi/src/github.com/okonomi/serverless-openapi-documenter-example/node_modules/.pnpm/serverless-openapi-documenter@0.0.113/node_modules/serverless-openapi-documenter/src/openAPIGenerator.js:144:13
    at async OpenAPIGenerator.generate (/Users/okonomi/src/github.com/okonomi/serverless-openapi-documenter-example/node_modules/.pnpm/serverless-openapi-documenter@0.0.113/node_modules/serverless-openapi-documenter/src/openAPIGenerator.js:143:26)
    at async PluginManager.runHooks (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1241:9549)
    at async PluginManager.invoke (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1241:10318)
    at async PluginManager.run (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1241:11047)
    at async Serverless.run (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1248:10523)
    at async runFramework (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1275:1777)
    at async TraditionalRunner.run (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1271:28313)
    at async route (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1302:2779)
    at async Object.run (file:///Users/okonomi/.serverless/releases/4.14.2/package/dist/sf-core.js:1303:3661)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/
```

**Desktop (please complete the following information):**
 - Serverless version: 4.14.2
 - serverless-openapi-documenter version: 0.0.113

**Additional context**

**Comment by alegarciadelrio** [comment]
@JaredCE just checking this issue. I replicated it, and gave me the opaque error.

The function `createUser` has `application/json: user`; which is the **key** of the model in this case, but the plugin resolves that string against the schema **name** instead. 

```yaml
schemas:
  user:            # <- the key, line 9
    name: User     # <- the API Gateway model name, line 10
```

Changing `name: User` to `name: user` (so the name match) generates successfully — I tested it and generated the file.


`standardiseModels()` iterates Object.keys(this.apiGatewayModels) but discards the `key`, keeping only the `model object`. So "user" is lost and the model is known only as "User".
https://github.com/JaredCE/serverless-openapi-documenter/blob/117bf046425091a081720dfe48a995d00f0c2d14/src/schemaHandler.js#L75-L79

Reading the documentation presented in the issue, the example is broken by this bug. 
The doc shows the intended resolution is matching by `key` and `name` is optional.
[Serverless Request Schema Validators](https://github.com/JaredCE/serverless-openapi-documenter?tab=readme-ov-file#serverless-request-schema-validators)

---

Thinking if it is ok for you do the resolution matching by key? Let me know, maybe I can help with a PR.

Thank you, 
Ale
