### ISSUE TITLE
[BUG] Handle multiple operation for same path

### ISSUE THREAD

**Issue by cbm-eheude** [JaredCE/serverless-openapi-documenter#28]
**Describe the bug**
For a same path only one operation can be managed

**To Reproduce**
```
functions:
  myLambda1:
  ...
  events:
    - httpApi:
        method: GET
        path: /user/{id}
  myLambda2:
  ...
  events:
    - httpApi:
        method: PUT
        path: /user/{id}
  ...
```
**Expected behavior**
Expected to have for same path both operations on generated file

**Desktop (please complete the following information):**
 - Framework Core: 2.72.3 (local)
 - Plugin: 5.5.4
 - SDK: 4.3.2
 - Components: 3.18.2
 - serverless-openapi-documenter version [e.g. 0.0.15]

**Additional context**
https://github.com/JaredCE/serverless-openapi-documenter/blob/359c2c535f3c3352696240730c21b739d8d193c6/src/definitionGenerator.js#L111

A possible solution
```
if (paths[slashPath]) {
    Object.assign(paths[slashPath], path);
} else {
    Object.assign(paths, {[slashPath]: path});
}
```
