### ISSUE TITLE
[BUG] An error is raised when openAPI variables used on server

### ISSUE THREAD

**Issue by cbm-eheude** [JaredCE/serverless-openapi-documenter#32]
**Describe the bug**
When I try to use this feature [here](https://swagger.io/specification/#server-object) an error is raised 

**To Reproduce**
On serverless.doc.yml
```
documentation:
  version: 1.0.0
  description: 'My API description'
  servers:
    - url: https://my.{env}.url
      description: Dev & Staging server
      variables:
        env:
          enum:
            - dev
            - stage
          default: dev
    - url: https://my.url
      description: Production server
  ...
```
**Expected behavior**
Variables managed on servers

**Desktop (please complete the following information):**
 - Serverless version: [e.g. 2.73.3]
 - serverless-openapi-documenter version [e.g. 0.0.17]

**Additional context**
Possible solution
On `createServers(servers)` function add 
```
if (server.variables) {
    obj.variables = server.variables
}
```

It is possible to do the same for authorization ?
https://swagger.io/specification/#security-scheme-object
