### ISSUE TITLE
[BUG] Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by PierrickI3** [JaredCE/serverless-openapi-documenter#51]
I get a `Cannot convert undefined or null to object` error when running `sls openapi generate`

This is the first time I am testing this. Great idea btw!!

```
serverless.yml

service: aws
#org: ccportal
app: aws
custom:
  documentation:
    version: '1'
    title: 'My API'
    description: 'This is my API'
    externalDocumentation:
      url: https://google.com
      description: A link to google
    servers:
      url: https://example.com
      description: The server
    tags:
      - name: tag1
        description: this is a tag
        externalDocumentation:
          url: https://npmjs.com
          description: A link to npm
    models:
      - name: 'SuccessResponse'
        description: 'Success response'
        content:
          application/json:
            schema: ${file(models/SuccessResponse.json)}
      - name: 'ErrorResponse'
        description: 'This is an error'
        content:
          application/json:
            schema: ${file(models/ErrorResponse.json)}
      - name: 'PutDocumentResponse'
        description: 'PUT Document response model (external reference example)'
        content:
          application/json:
            schema: ${file(models/PutDocumentResponse.json)}
      - name: 'PutDocumentRequest'
        description: 'PUT Document request model (inline example)'
        content:
          application/json:
            schema:
              $schema: 'http://json-schema.org/draft-04/schema#'
              properties:
                SomeObject:
                  type: 'object'
                  properties:
                    SomeAttribute:
                      type: 'string'
  secrets_AWS: ${ssm:/aws/reference/secretsmanager/ccportal/aws}
  serverless-offline:
    httpPort: 4000
    # useChildProcesses: true # Do not use with this API as it has unexpected effects (API won't respond any more)
  prune:
    automatic: true
    number: 1
  cors-config:
    origins:
      - '*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - env
      - token
    allowCredentials: false
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 8192
  profile: ccportal
  lambdaHashingVersion: '20201221'
  stage: dev
  region: eu-central-1
  deploymentBucket:
    name: my.dev.serverless.deploys
  versionFunctions: false
  tracing:
    lambda: true
  logRetentionInDays: 7
  timeout: 30 # If using web sockets, you can increase this. It will cause a warning when running 'serverless deploy' but you can ignore it.
  environment:
    NODE_ENV: ${file(./.env.yml):${opt:stage, self:provider.stage}.NODE_ENV}
    AWS_ACCOUNT_ID: ${self:custom.secrets_AWS.ACCOUNT_ID}
    AWS_QUICKSIGHT_USER_ARN: ${self:custom.secrets_AWS.quickSight_user_arn}
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - dynamodb:*
        - s3:*
        - quicksight:GetDashboardEmbedUrl
        - quicksight:GetAnonymousUserEmbedUrl
        - quicksight:GenerateEmbedUrlForRegisteredUser
        - quicksight:ListDashboards
      Resource:
        - '*'
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${opt:stage, self:provider.stage}-CCPortalGW-restApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${opt:stage, self:provider.stage}-CCPortalGW-rootResourceId
functions:
  getQuickSightDashboardUrl:
    handler: handler.getQuickSightDashboardUrl
    events:
      - http:
          path: aws/quicksight/dashboardUrl/{id}
          method: get
          cors: ${self:custom.cors-config}
          documentation:
            summary: 'Get a QuickSight dasbhoard URL'
            description: 'Used to get a QuickSight dashboard URL based on its id'
            tags:
              - aws
              - quicksights
            pathParams:
              - name: 'id'
                description: 'The QuickSight dashboard id'
                schema:
                  type: 'string'
                  pattern: '^[-a-z0-9_]+$'
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: 'Success'
  getDashboardList:
    handler: handler.listdashboards
    events:
      - http:
          path: aws/quicksight/dashboards
          method: get
          cors: ${self:custom.cors-config}
          documentation:
            summary: 'Get a list of QuickSight dasbhoards'
            description: 'Gets the list of QuickSights dashboards'
            tags:
              - aws
              - quicksights
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: 'Success'
  getQuickSightSearchBar:
    handler: handler.getQuickSightSearchBar
    events:
      - http:
          path: aws/quicksight/searchBarUrl/{id}
          method: get
          cors: ${self:custom.cors-config}
          documentation:
            summary: 'Gets a QuickSights search bar URL'
            description: 'Used to get a QuickSights search bar URL based on its id'
            tags:
              - aws
              - quicksights
            pathParams:
              - name: 'id'
                description: 'The QuickSight search bar id'
                schema:
                  type: 'string'
                  pattern: '^[-a-z0-9_]+$'
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: 'Success'
                responseModels:
                  application/json: 'SuccessResponse'

package:
  exclude:
    - .dynamodb/**
    - .nyc_output/**
    - coverage/**
    - test/**
    - .git/**
    - serverless.yml
    - .serverless/**
    - requests.http
    - snowflake.log
    - node_modules/puppeteer/.local-chromium/**
plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-common-excludes
  - serverless-openapi-documenter

```
**Expected behavior**
Generate an OpenAPI file and a Postman collection file

**Output from running `sls openapi generate`**

```console
$sls openapi generate

Running "serverless" from node_modules
OpenAPI v3 Document Generation
[OPTIONS]
  openApiVersion: "3.0.0"
  format: "json"
  output file: "openapi.json"
  indentation: "2"

✖ ERROR: An error was thrown generating the OpenAPI v3 documentation
Environment: linux, node 16.13.1, framework 3.18.2 (local) 3.22.0v (global), plugin 6.2.2, SDK 4.3.2
Credentials: Local, "ccportal" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
TypeError: Cannot convert undefined or null to object

```
