### ISSUE TITLE
[BUG] Schema object cannot have additionalProperty: Status

### ISSUE THREAD

**Issue by PierrickI3** [JaredCE/serverless-openapi-documenter#55]
**Describe the bug**

Can't have `Status` field in methodResponse model

**To Reproduce**

If a `Status` field is present in the response model, I get this error:

```console
Error:
AssertionError: Schema object cannot have additionalProperty: Status
```

```
SuccessResponse.json

{
  "Status": 200,
  "EmbedUrl": "url",
  "RequestId": "b35fc1ff-578b-4bb4-a975-1abe5574da1b"
}
```

Here is where it's used in my serverless.yml file:

```yaml
functions:
  getQuickSightDashboardUrl:
    handler: handler.getQuickSightDashboardUrl
    events:
      - http:
          path: aws/quicksight/dashboardUrl/{id}
          method: get
          cors: ${self:custom.cors-config}
          documentation:
            summary: 'Get a QuickSight dasbhoard URL'
            description: 'Used to get a QuickSight dashboard URL based on its id'
            tags:
              - aws
              - quicksights
            pathParams:
              - name: 'id'
                description: 'The QuickSight dashboard id'
                schema:
                  type: 'string'
                  pattern: '^[-a-z0-9_]+$'
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: 'Success'
                responseModels:
                  application/json: 'SuccessResponse'
```

From my point of view, you should not check if a field in the response model contains duplicate fields?
