### ISSUE TITLE
[BUG] requestHeaders not in output openapi.json file

### ISSUE THREAD

**Issue by PierrickI3** [JaredCE/serverless-openapi-documenter#56]
**Describe the bug**

After adding a `requestHeaders` section, it does not make it in the output file

**To Reproduce**

```
serverless.yml (extract)

documentation:
            summary: 'Get a QuickSight dasbhoard URL'
            description: 'Used to get a QuickSight dashboard URL based on its id'
            requestHeaders:
              - name: 'env'
                description: 'Genesys Cloud environment (e.g. mypurecloud.com)'
                schema:
                  type: 'string'
              - name: 'token'
                description: 'Genesys Cloud OAuth token'
                schema:
                  type: 'string'
            pathParams:
              - name: 'id'
                description: 'The QuickSight dashboard id'
                schema:
                  type: 'string'
                  pattern: '^[-a-z0-9_]+$'
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: 'Success'
                responseModels:
                  application/json: 'SuccessResponse'

```
**Expected behavior**

Request headers (here, `env` and `token`) should be in the `openapi.json` file but they are not.

`sls openapi generate` does not output any errors.

**Comment by JaredCE** [comment]
Ahh that is a documentation issue, I need to fix that.  For now `requestHeaders` should be called `headerParams`:

```
headerParams:
  - name: 'env'
    description: 'Genesys Cloud environment (e.g. mypurecloud.com)'
    schema:
      type: 'string'
  - name: 'token'
    description: 'Genesys Cloud OAuth token'
    schema:
      type: 'string'
```

I have a feeling that `responseHeaders` hasn't quite been implemented and so probably does not work currently.  Will make some updates to code and documentation when I get some time.
