### ISSUE TITLE
[BUG] Not able to reference models from other models

### ISSUE THREAD

**Issue by PierrickI3** [JaredCE/serverless-openapi-documenter#58]
One more question: How do you reference an array of models in a response? I have the following in custom/documentation/models:

```
      - name: DashboardsSuccessResponse
        description: Dashboards Success response
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/custom/documentation/models/DashboardItem' <-- This fails
      - name: DashboardItem
        description: Dashboard item
        content:
          properties:
            Arn:
              type: string
            DashboardId:
              type: string
            Name:
              type: string
            CreatedTime:
              type: string
            LastUpdatedTime:
              type: string
            PublishedVersionNumber:
              type: number
            LastPublishedTime:
              type: string
```

Response is an array of `DashboardItem` but I am not sure how to reference it in the `DashboardsSuccessResponse` model.

Thanks!

**Comment by JaredCE** [comment]
@PierrickI3 So first thing, `DashboardItem` is going to fail because you need to write it like:

```
content:
  application/json:
    schema:
      ....
```

Now, I've managed to do this by fudging the `yaml` a little bit.  It should/could probably behave better, but this will fix the current issue, even though it's a bit of a plaster.  The models and JSON schema stuff needs a deeper look but for now this is how you can do it.

```
- name: DashboardItem
        description: Dashboard item
        content:
          application/json:
            schema: &arrayItem
              properties:
                Arn:
                  type: string
                DashboardId:
                  type: string
                Name:
                  type: string
                CreatedTime:
                  type: string
                LastUpdatedTime:
                  type: string
                PublishedVersionNumber:
                  type: number
                LastPublishedTime:
                  type: string

      - name: DashboardsSuccessResponse
        description: Dashboards Success response
        content:
          application/json:
            schema:
              type: array
              items: *arrayItem

```

You'll see on `DashboardItem` i have added a property(?) next to `schema`: **&arrayItem**, this then allows me to reference it in `DashboardsSuccessResponse` next to `items`.  

From my experiments, you have to define `&uniqueName` before using them with `*uniqueName`, it won't work after.  

I used this stackoverflow question/answer for guidance: https://stackoverflow.com/questions/2063616/how-to-reference-a-yaml-setting-from-elsewhere-in-the-same-yaml-file

As I say, the models/JSON schemas need a deeper look and while this might work for you right now, other things might fail because it's a bit house of cards.  But being able to reference other models should be something I can fix when I get some time, but is probably a big fix.
