### ISSUE TITLE
Feature request: additional info attributes

### ISSUE THREAD

**Issue by josipoviciwan** [JaredCE/serverless-openapi-documenter#66]
In OpenAPI the info section can contain a lot more than title, version and description. It would be nice if among other OpenAPI standard attributes which are still missing, in example contact:

```
 "contact": {
    "name": "API Support",
    "url": "http://www.example.com/support",
    "email": "support@example.com"
  }
```

there was the possibility to include custom attributes as well, for instance 

```
  x-api-id: e9bc9584aasdsd4380-860a-9asd7495de6f200
  x-audience: company-internal
  x-logo:
    url: 'https://www.google.de/wp-content/logo/logo-black.svg'
    altText: company logo
```

If we want to provide a list of attributes that we want to include in the output file info section we can do something like this:

```
serverless.docs.yml

documentation:
 contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  x-api-id: e9bc9584aasdsd4380-860a-9asd7495de6f200
  x-audience: company-internal
  x-logo:
    url: 'https://www.google.de/wp-content/logo/logo-black.svg'
    altText: company logo
  additionalInfoAttributes:
    - x-api-id
    - x-audience
    - contact
    - x-logo
```

Update the implementation to something like this:

```
definitionGenerator.js

    createInfo() {
        const service = this.serverless.service
        const documentation = this.serverless.service.custom.documentation;
        const additionalInfoAttributes = documentation?.additionalInfoAttributes || [];

        const info = {
            title: documentation?.title || service.service,
            description: documentation?.description || '',
            version: documentation?.version || uuid(),
        }

        for (const attribute of additionalInfoAttributes){
            info[attribute] = documentation[attribute];
        }  
        
        Object.assign(this.openAPI, {info})
    }
```
BR,
Iwan
