### ISSUE TITLE
Feature request: bearer security

### ISSUE THREAD

**Issue by josipoviciwan** [JaredCE/serverless-openapi-documenter#70]
It would be nice if we could define root level security for OpenAPI. One of the most commonly used is the following:

```
security:
  - BearerAuth: []
  
components:
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
```
