### ISSUE TITLE
$ref inside models is not working across files

### ISSUE THREAD

**Issue by TobiaZambon** [JaredCE/serverless-openapi-documenter#97]
Hi, I'm generating my model list using a script that creates a `modelList.yml` file which contains the list of file where my models are described. 
every model is then described inside a file `ClassName.json`. I'm using `$ref` to reference a model that is contained in a different file.

Example:
serverless.yml:

```
custom:
  modelsList: ${file(resources/models/modelList.yml)}
  documentation:
    [...]
functions:
  AgencyList:
    name: bla
    handler: bla
    events:
      - http:
          path: api/v1/agencies
          method: get
          documentation:
            summary: "Gets the agency list"
            methodResponses:
              - statusCode: 200
                responseModels:
                  application/json: "AgencyList"
                responseBody:
                  description: "Test"
```

file modelList.yml:
```
---
- name: "Agency"
  description: "This is a Agency"
  contentType: "application/json"
  schema: "${file(resources/models/Agency.json)}"
- name: "AgencyList"
  description: "This is a AgencyList"
  contentType: "application/json"
  schema: "${file(resources/models/AgencyList.json)}"
```

file AgencyList.json:
```
{
  "type" : "object",
  "properties" : {
    "agencies" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/Agency"
      }
    }
  }
}
```

file Agency.json:
```
{
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string"
    }
  }
}
```

When I run the command to generate the OpenAPI documentation I'm getting this error:
`ServerlessError: MissingPointerError: Token "components" does not exist.` like if `$ref` could be linked only to other properties of the same file (because as far as I debugged, it is searching `components`,`schema`,`Agency `inside the properties of the same file)

The same configuration was working with the deprecated plugin "serverless-openapi-documentation".

Is there a way to solve this?
thanks a lot
